require 'mkmf'
require_relative 'support'

desc 'Verifies the requirements'
task :requirements do
  verify_requirements
end

task :default => :requirements do
  perl_extensions.each do |directory|
    compile_perl_extension(directory)
  end
end
